version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    tty: true  # Оставить для отладки; можно убрать
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        poetry run python manage.py migrate &&
        poetry run python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  pg_data:
